<?php

/**
 * @file stripe.module
 * Drupal hooks used for integrating the Stripe service.
 */

/**
 * Implements hook_help().
 */
function stripe_help($path, $arg) {
  if ($path == 'admin/config/stripe/keys') {
    $output = '<ol>';
    $output .= '<li>' . t('Enter the API keys you get from your <a href="@url">Stripe account page</a>.', array('@url' => 'https://manage.stripe.com/account')) . '</li>';
    $output .= '<li>' . t('Use the radio buttons to choose which API Key should be used with this site.') . '</li>';
    $output .= '<li>' . t('After designating an API Key, you might want to try out <a href="@url">the test form</a>.', array('@url' => '/admin/config/stripe/test')) . '</li>';
    $output .= '</ol>';
    return $output;
  }
  if ($path == 'admin/config/stripe/test') {
    return '<p>' . t('This form is to test responses from Stripe. The default values are accepted by Stripe for testing purposes. Before you can use this form, you should <a href="@url">designate an active API Key</a>.', array('@url' => '/admin/config/stripe/keys')) . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function stripe_permission() {
  return array('administer stripe');
}

/**
 * Implementation of hook_init().
 */
function stripe_init() {
	$stripe_lib_path = function_exists('libraries_get_path') ? libraries_get_path('facebook-php-sdk') : 'sites/all/libraries/stripe-php';
	$stripe_api = variable_get(STRIPE_API_FILE, $stripe_lib_path . '/lib/Stripe.php');
	
	try {
		if( ! class_exists('Stripe') && ! include($stripe_api) ) {
			drupal_set_message(t('Please install the Stripe PHP library per the instructions in the README.', 'error'));
			return;
		}
		
		drupal_set_html_head('<script src="'. check_url(url('https://js.stripe.com/v1/', array('query' => $query))) .'" type="text/javascript"></script>');
	} catch(Exception $e) {
		watchdog('warn', t('Could not load Stripe library. %e', array('%e' => $e)));
	}
}

/**
 * Implements hook_menu().
 */
function stripe_menu() {
  $items['admin/stripe'] = array(
    'title' => 'Stripe',
    'description' => 'List of what the stripe module offers.',
    'position' => 'right',
    'page callback' => 'stripe_admin_menu',
    'access arguments' => array('administer stripe'),
    'weight' => -10,
    'file' => 'stripe.admin.inc',
  );

  $items['admin/stripe/keys'] = array(
    'title' => 'Configuration',
    'description' => 'Enter API Keys and set which one should be active.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stripe_admin_keys'),
    'access arguments' => array('administer stripe'),
    'file' => 'stripe.admin.inc',
  );

  $items['admin/stripe/test'] = array(
    'title' => 'Test form',
    'description' => 'A form for testing Stripe responses.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stripe_admin_test'),
    'access arguments' => array('administer stripe'),
    'file' => 'stripe.admin.inc',
  );
  
  $items['admin/stripe/payments'] = array(
    'title' => 'Payments',
    'description' => 'A list of payments received.',
    'page callback' => 'stripe_admin_payments',
    'access arguments' => array('administer stripe'),
    'file' => 'stripe.admin.inc',
  );

  return $items;
}